---    
- name: generate a private copy of /etc/hosts
  hosts: all
  become: yes
        
  tasks:
    - name: loop over inventory
      template:
        src: hosts.j2
        dest: /etc/myhosts
      when: inventory_hostname in groups['dev']
